config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "welcome#index"
  resources :users
  resources :sessions

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  validates_presence_of :name, :email, :password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    redirect_to root_path
    flash[:succsess] = "You have successfully logged in"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create

    @user = User.new(user_params)
    if @user.save
      flash[:success] = "You have successfully registered"
    else
      render :new
      flash[:error] = "you suck"
    end
    redirect_to root_path
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

def index
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Auth</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"> <%= value %></div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.label :email %>
<%= f.email_field :email %>
<%= f.label :password %>
<%= f.text_field :password %>
<%= f.submit %>
<% end %>

app/views/welcome/index.html.erb
<%= link_to "Register", new_user_path %>
<%= link_to "Log In", new_session_path%>